version: '3.8'

services:
  app:
    container_name: nestmart-api
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - kafka

  postgres:
    image: postgres:15
    container_name: nestmart-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nestmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nestmart-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nestmart-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # web UI

  kafka:
    image: bitnami/kafka:latest
    container_name: nestmart-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: nestmart-zookeeper
    ports:
      - "2181:2181"

volumes:
  pgdata:
